@BASE_URL=http://[::1]:5173

@AUTHOR_ID=638e7f5ac61f8b6b0dabee63

###
GET {{BASE_URL}}/api/authors


###
GET {{BASE_URL}}/api/authors/{{AUTHOR_ID}}

###
POST {{BASE_URL}}/api/authors
content-type: application/json

{
    "firstName": "Phone",
    "lastName": "Waiyam Hein",
    "penName": "broccoli",
    "intro": "songs and stawberries",
    "bio": "art, love, maths and freedom",
    "slug": "",
    "image": "",
    "thumbnail": ""
}

###
PUT {{BASE_URL}}/api/authors/{{AUTHOR_ID}}
content-type: application/json

{
    "firstName": "Phone",
    "lastName": "Waiyam Hein",
    "penName": "broccoli",
    "intro": "songs and stawberries",
    "bio": "art, love, maths and freedom",
    "slug": "broccoli",
    "image": "",
    "thumbnail": ""
}