# @BASE_URL=http://[::1]:5173
@BASE_URL=http://localhost:5173

@AUTHOR_ID=63ce5059abeec0b8a657e76b

###
GET {{BASE_URL}}/api/authors


###
GET {{BASE_URL}}/api/authors/{{AUTHOR_ID}}

###
POST {{BASE_URL}}/api/authors
content-type: application/json

{
    "firstName": "Aung Phone",
    "lastName": "Maw",
    "penName": "apm",
    "intro": "hegalian",
    "bio": "fucked up shitpost",
    "slug": "",
    "image": "",
    "thumbnail": ""
}

###
PUT {{BASE_URL}}/api/authors/{{AUTHOR_ID}}
content-type: application/json

{
    "firstName": "Ludwig",
    "lastName": "Yool"
}