@BASE_URL=http://[::1]:5173
@SOCIAL_ID=

###
GET {{BASE_URL}}/api/socials


###
GET {{BASE_URL}}/api/socials/{{SOCIAL_ID}}

###
POST {{BASE_URL}}/api/socials
content-type: application/json

{
    "url": "",
    "icon": "",
    "name": "",
}

###
PUT {{BASE_URL}}/api/socials/{{SOCIAL_ID}}
content-type: application/json

{
    "url": "",
    "icon": "",
    "name": "",
}