export const AUTHOR_COLLECTION = "authors"
export const SOCIAL_COLLECTION = "socials"
export const SONG_COLLECTION = "songs"
export const POST_COLLECTION = "posts"
export const CONTEXT_COLLECTION = "contexts"